#!/bin/sh
change(){
	git filter-branch --env-filter '

	OLD_EMAIL="'$OLD_EMAIL'"
	CORRECT_NAME="Jane42070"
	CORRECT_EMAIL="'$CORRECT_EMAIL'"

	if [ "$GIT_COMMITTER_EMAIL" = "$OLD_EMAIL" ]
	then
		export GIT_COMMITTER_NAME="$CORRECT_NAME"
		export GIT_COMMITTER_EMAIL="'$CORRECT_EMAIL'"
	fi
	if [ "$GIT_AUTHOR_EMAIL" = "$OLD_EMAIL" ]
	then
		export GIT_AUTHOR_NAME="$CORRECT_NAME"
		export GIT_AUTHOR_EMAIL="'$CORRECT_EMAIL'"
	fi
	' --tag-name-filter cat -- --branches --tags
}

[ ! -d ".git" ] && echo "Not a git repository, check your current location or back to root git directory" && exit
GOON=0
echo "Change commit info"
while [[ $GOON != "y" ]]; do
	read -p "Input old email:" OLD_EMAIL
	read -p "Input correct email:" CORRECT_EMAIL
	read -p "Input correct name:" CORRECT_NAME
	echo "Name: $CORRECT_NAME"
	echo "Email: $OLD_EMAIL -> $CORRECT_EMAIL"
	read -p "Are you sure?(y/n)" GOON
done
change
