#!/bin/bash
disk=`df -h | awk '{if ($6 == "/") print $1}'`
echo 💾$(df -h | awk '{if($1=="'$disk'") print $5}')
["$1" == ""] && exit
case $1 in
	1) st -i -e "lf";;
	3) st -e "nvim" "$0";;
	4) st -i -e "yay" "-Scc" && notify-send -t 1000 "成功清理缓存";;
esac
