#!/bin/sh
# 下载速度
while true; do
	predown=$(cat /sys/class/net/enp*/statistics/rx_bytes | awk '{printf "%.1f", $0/1024}')
	preup=$(cat /sys/class/net/enp*/statistics/tx_bytes | awk '{printf "%.1f", $0/1024}')
	sleep 1
	nowdown=$(cat /sys/class/net/enp*/statistics/rx_bytes | awk '{printf "%.1f", $0/1024}')
	nowup=$(cat /sys/class/net/enp*/statistics/tx_bytes | awk '{printf "%.1f", $0/1024}')
	if [[ $nowdown != $predown ]]; then
		echo $(echo $nowdown $predown|awk 'a=$1-$2{if (a > 1024) {printf "%.1fMB", a/1024}else {printf "%.1fKB", a}}') $(echo $nowup $preup|awk 'a=$1-$2{if (a > 1024) {printf "%.1fMB", a/1024}else {printf "%.1fKB", a}}')
	else
		echo 0.0KB
	fi
done
