#!/bin/sh
package=`yay -Qu | wc -l`
case $1 in
	1) 
		notify-send "Synchronizing package databases..." && yay -Sy > /dev/null 2>&1 && package=`yay -Qu | wc -l` && sigdwmblocks 9;;
	2)  ;;
	3) "st" -e "nvim" "$0";;
esac
echo 📦$package
