#!/bin/bash
voice=`pulsemixer --get-volume | awk '{print $1}'`
if [[ $voice == 0 ]]; then
	echo 🔇${voice}
elif [[ $voice < 40 ]]; then
	echo 🔈${voice}
elif [[ $voice < 70 ]]; then
	echo 🔉${voice}
else
	echo 🔊${voice}
fi
