#!/bin/sh
case $1 in
	1) "st" -i -g float -e "pulsemixer" && sigdwmblocks 1 && exit;;
	2) pamixer -t && sigdwmblocks 1 && exit;;
	3) "st" -e "nvim" "$0";;
esac
[ $(pamixer --get-mute) = true ] && echo 🔇 && exit
voice="$(pamixer --get-volume)"
if [[ "$voice" -lt "35" ]]; then
	echo 🔈${voice}
elif [[ "$voice" -lt "70" ]]; then
	echo 🔉${voice}
else
	echo 🔊${voice}
fi
