#!/bin/sh
feh --bg-fill --no-fehbg --randomize /home/$(whoami)/Github/wallpapers/*
["$1" == ""] && exit
# case $1 in
#     1)
#         feh --bg-fill --no-fehbg --randomize /home/$(whoami)/github/wallpapers/*
#         && notify-send "Wallpaper changed"
#         ;;
#     2)
#         notify-send -t "左键更换壁纸\n右键编辑脚本\n中键查看帮助";;
#     3) "st" -e "nvim" "$0";;
# esac
