#!/bin/sh
pos="chongqing"
echo $(curl -s "wttr.in/$pos?format=%c%t")
[ "$1" == "" ] && exit
curl -s "wttr.in/$pos" > /tmp/weather
case $1 in
	1) st -i -g 125x30 -e "bat" "--style=plain" "/tmp/weather";;
	2) ;;
	3) ;;
esac
