#!/bin/sh
if [[ users == "root" ]]; then
	str='ACTION=="add", SUBSYSTEM=="backlight", KERNEL=="<vendor>", RUN+="/bin/chgrp video /sys/class/backlight/%k/brightness"
ACTION=="add", SUBSYSTEM=="backlight", KERNEL=="<vendor>", RUN+="/bin/chmod g+w /sys/class/backlight/%k/brightness"'
	echo $str > /etc/udev/rules.d/backlight.rules
	echo "done!"
	exit 0
else
	echo "must be running as root! exiting..."
	exit -1
fi
	
